apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    io.kompose.service: pfcon
  name: pfcon
spec:
  ports:
  - name: "5005"
    port: 5005
    targetPort: 5005
  selector:
    io.kompose.service: pfcon
status:
  loadBalancer: {}
