apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: queue
  name: queue
spec:
  containers:
    - image: rabbitmq:3
      name: queue
      resources:
        limits:
          cpu: "200m"
          memory: "512Mi"
        requests:
          cpu: "200m"
          memory: "512Mi"
  restartPolicy: OnFailure
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: queue
  labels:
    app: queue
    env: production
spec:
  selector:
    app: queue
    env: production
  ports:
    - port: 5672
      targetPort: 5672