apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    org.chrisproject.miniChRIS: miniChRIS
    org.chrisproject.role: ChRIS ultron backEnd
  creationTimestamp: null
  labels:
    io.kompose.service: chris
  name: chris
spec:
  replicas: 1
  selector:
    io.kompose.service: chris
  strategy:
    resources: {}
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/local: "true"
        io.kompose.service: chris
    spec:
      containers:
        - env:
            - name: DJANGO_COLLECTSTATIC
              value: "on"
            - name: DJANGO_DB_MIGRATE
              value: "on"
          image: ' '
          name: chris
          ports:
            - containerPort: 8000
          resources: {}
      restartPolicy: Always
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - chris
        from:
          kind: ImageStreamTag
          name: chris:next-3.0.0.a9
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
