apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.network/local: "true"
    io.kompose.service: chris-db
  name: chris-db
spec:
  containers:
    - image: postgres:13
      name: chris_db
      resources: {}
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: chris-db-data
  restartPolicy: OnFailure
  volumes:
    - name: chris-db-data
      persistentVolumeClaim:
        claimName: chris-db-data
status: {}
