apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: chris
  name: chris
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations: null
      from:
        kind: DockerImage
        name: fnndsc/cube:next-3.0.0.a9
      generation: null
      importPolicy: {}
      name: next-3.0.0.a9
      referencePolicy:
        type: ""
status:
  dockerImageRepository: ""
