apiVersion: v1
kind: Service
metadata:
  annotations:
    org.chrisproject.miniChRIS: miniChRIS
    org.chrisproject.role: ChRIS ultron backEnd
  creationTimestamp: null
  labels:
    io.kompose.service: chris
  name: chris
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: chris
status:
  loadBalancer: {}
