apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.network/local: "true"
    io.kompose.service: scheduler
  name: scheduler
spec:
  containers:
    - args:
        - celery
        - -A
        - core
        - beat
        - -l
        - info
        - --scheduler
        - django_celery_beat.schedulers:DatabaseScheduler
      env:
        - name: DJANGO_COLLECTSTATIC
          value: "off"
        - name: DJANGO_DB_MIGRATE
          value: "off"
      image: fnndsc/cube:next-3.0.0.a9
      name: scheduler
      resources: {}
  restartPolicy: OnFailure
status: {}
