apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: swift
  name: swift
spec:
  replicas: 1
  selector:
    io.kompose.service: swift
  strategy:
    resources: {}
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/local: "true"
        io.kompose.service: swift
    spec:
      containers:
        - env:
            - name: SWIFT_KEY
              value: testing
            - name: SWIFT_USERNAME
              value: chris:chris1234
          image: ' '
          name: swift
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /srv
              name: swift-storage
      restartPolicy: Always
      volumes:
        - name: swift-storage
          persistentVolumeClaim:
            claimName: swift-storage
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - swift
        from:
          kind: ImageStreamTag
          name: swift:latest
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
