apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.network/local: "true"
    io.kompose.service: worker-periodic
  name: worker-periodic
spec:
  containers:
    - args:
        - celery
        - -A
        - core
        - worker
        - -c
        - "2"
        - -l
        - info
        - -Q
        - periodic
      env:
        - name: DJANGO_COLLECTSTATIC
          value: "off"
        - name: DJANGO_DB_MIGRATE
          value: "off"
      image: fnndsc/cube:next-3.0.0.a9
      name: worker_periodic
      resources: {}
  restartPolicy: OnFailure
status: {}
