apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: chris-ui
  name: chris-ui
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations: null
      from:
        kind: DockerImage
        name: ghcr.io/fnndsc/chris_ui:20220601
      generation: null
      importPolicy: {}
      name: "20220601"
      referencePolicy:
        type: ""
status:
  dockerImageRepository: ""
