apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: chris-ui
  name: chris-ui
spec:
  replicas: 1
  selector:
    io.kompose.service: chris-ui
  strategy:
    resources: {}
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: chris-ui
    spec:
      containers:
        - args:
            - sirv
            - --quiet
            - --single
          env:
            - name: REACT_APP_CHRIS_UI_URL
              value: http://localhost:8000/api/v1/
          image: ' '
          name: chris_ui
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - chris-ui
        from:
          kind: ImageStreamTag
          name: chris-ui:20220601
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
