apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: chris-store-ui
  name: chris-store-ui
spec:
  replicas: 1
  selector:
    io.kompose.service: chris-store-ui
  strategy:
    resources: {}
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: chris-store-ui
    spec:
      serviceAccountName: pipeline
      containers:
        - args:
            - sirv
            - --quiet
            - --single
          env:
            - name: REACT-APP-STORE-URL
              value: http://localhost:8010/api/v1/
          image: docker.io/fnndsc/chris_store_ui:latest
          name: chris-store-ui
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
