apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: chris-dev-db
  name: chris-dev-db
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations: null
      from:
        kind: DockerImage
        name: postgres:13
      generation: null
      importPolicy: {}
      name: "13"
      referencePolicy:
        type: ""
status:
  dockerImageRepository: ""
