apiVersion: apps/v1
kind: Deployment
metadata:
  name: chris-store-db
  labels:
    app: chris-store-db
spec:
  replicas: 1  # stateful service, so only a single replica must be used
  selector:
    matchLabels:
      app: chris-store-db
  template:
    metadata:
      name: chris-store-db
      labels:
        app: chris-store-db
    spec:
      serviceAccountName: pipeline
      containers:
        - name: chris-store-db
          image: postgres:13
          ports:
            - containerPort: 5432
          resources:
            limits:
              cpu: "100m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
          envFrom:
            - configMapRef:
                name: chris-store-db-secrets-env
          volumeMounts:
            - name: chrisdb
              mountPath: "/var/lib/postgresql"
      # Mount a persistent volume onto ChRIS DB
      volumes:
        - name: chrisdb
          persistentVolumeClaim:
            claimName: chris-store-db-data

