apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: chris-store-ui
  name: chris-store-ui
spec:
  replicas: 1
  selector:
    io.kompose.service: chris-store-ui
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: chris-store-ui
    spec:
      containers:
        - args:
            - sirv
            - --quiet
            - --single
          env:
            - name: REACT_APP_STORE_URL
              value: http://localhost:8010/api/v1/
          image: 'docker.io/fnndsc/chris_store_ui:0.2.0-rc.1'
          name: chris_store_ui
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
