apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
  name: chris-store
spec:
  replicas: 1
  selector:
    io.kompose.service: chris-store
  strategy:
    resources: {}
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/local: "true"
        io.kompose.service: chris-store
    spec:
      serviceAccountName: pipeline
      containers:
        - name: chris-store
          image: ghcr.io/fnndsc/chris_store:latest
          envFrom:
            - configMapRef:
                name: chris-store-ui-secrets-env
          ports:
            - containerPort: 8010
          resources:
            limits:
              cpu: "100m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
      restartPolicy: Always
status: {}
