apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: chris-ui
  name: chris-ui
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: ghcr.io/fnndsc/chris_ui:20220412
    generation: null
    importPolicy: {}
    name: "20220412"
status:
  dockerImageRepository: ""
