apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose convert --provider openshift --file docker-compose-cube-latest.yaml
    kompose.version: 1.17.0 (HEAD)
    org.chrisproject.miniChRIS: miniChRIS
    org.chrisproject.role: ChRIS ultron backEnd
  creationTimestamp: null
  labels:
    io.kompose.service: chris
  name: chris
spec:
  replicas: 1
  selector:
    io.kompose.service: chris
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: chris
    spec:
      containers:
      - env:
        - name: CELERY_BROKER_URL
          valueFrom:
            configMapKeyRef:
              key: CELERY_BROKER_URL
              name: chris-secrets-env
        - name: CHRIS_STORE_URL
          valueFrom:
            configMapKeyRef:
              key: CHRIS_STORE_URL
              name: chris-secrets-env
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              key: DATABASE_HOST
              name: chris-secrets-env
        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              key: DATABASE_PORT
              name: chris-secrets-env
        - name: DJANGO_ALLOWED_HOSTS
          valueFrom:
            configMapKeyRef:
              key: DJANGO_ALLOWED_HOSTS
              name: chris-secrets-env
        - name: DJANGO_COLLECTSTATIC
          value: "on"
        - name: DJANGO_CORS_ORIGIN_ALLOW_ALL
          valueFrom:
            configMapKeyRef:
              key: DJANGO_CORS_ORIGIN_ALLOW_ALL
              name: chris-secrets-env
        - name: DJANGO_CORS_ORIGIN_WHITELIST
          valueFrom:
            configMapKeyRef:
              key: DJANGO_CORS_ORIGIN_WHITELIST
              name: chris-secrets-env
        - name: DJANGO_DB_MIGRATE
          value: "on"
        - name: DJANGO_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              key: DJANGO_SECRET_KEY
              name: chris-secrets-env
        - name: DJANGO_SECURE_PROXY_SSL_HEADER
          valueFrom:
            configMapKeyRef:
              key: DJANGO_SECURE_PROXY_SSL_HEADER
              name: chris-secrets-env
        - name: DJANGO_SETTINGS_MODULE
          valueFrom:
            configMapKeyRef:
              key: DJANGO_SETTINGS_MODULE
              name: chris-secrets-env
        - name: DJANGO_USE_X_FORWARDED_HOST
          valueFrom:
            configMapKeyRef:
              key: DJANGO_USE_X_FORWARDED_HOST
              name: chris-secrets-env
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_DB
              name: chris-secrets-env
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PASSWORD
              name: chris-secrets-env
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_USER
              name: chris-secrets-env
        - name: STATIC_ROOT
          valueFrom:
            configMapKeyRef:
              key: STATIC_ROOT
              name: chris-secrets-env
        - name: SWIFT_AUTH_URL
          valueFrom:
            configMapKeyRef:
              key: SWIFT_AUTH_URL
              name: chris-secrets-env
        - name: SWIFT_CONTAINER_NAME
          valueFrom:
            configMapKeyRef:
              key: SWIFT_CONTAINER_NAME
              name: chris-secrets-env
        - name: SWIFT_KEY
          valueFrom:
            configMapKeyRef:
              key: SWIFT_KEY
              name: chris-secrets-env
        - name: SWIFT_USERNAME
          valueFrom:
            configMapKeyRef:
              key: SWIFT_USERNAME
              name: chris-secrets-env
        image: ' '
        name: chris
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - chris
      from:
        kind: ImageStreamTag
        name: chris:next-3.0.0.a3.git.0e516b6
    type: ImageChange
status: {}
