apiVersion: v1
kind: Service
metadata:
  annotations:
    name: ChRIS_store
    role: Chris store service
  creationTimestamp: null
  labels:
    io.kompose.service: chris-store
  name: chris_store
spec:
  ports:
    - name: "8010"
      port: 8010
      targetPort: 8010
  selector:
    io.kompose.service: chris-store
status:
  loadBalancer: {}
