apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose convert --provider openshift --file docker-compose-cube-latest.yaml
    kompose.version: 1.17.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: chris-ui
  name: chris-ui
spec:
  replicas: 1
  selector:
    io.kompose.service: chris-ui
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: chris-ui
    spec:
      containers:
      - args:
        - sirv
        - --quiet
        - --single
        env:
        - name: REACT_APP_CHRIS_UI_URL
          value: http://localhost:8000/api/v1/
        image: ' '
        name: chris-ui
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - chris-ui
      from:
        kind: ImageStreamTag
        name: chris-ui:20220412
    type: ImageChange
status: {}
