apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: chrisomatic
  name: chrisomatic
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations: null
      from:
        kind: DockerImage
        name: ghcr.io/fnndsc/chrisomatic:0.2.1
      generation: null
      importPolicy: {}
      name: 0.2.1
      referencePolicy:
        type: ""
status:
  dockerImageRepository: ""
