apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    name: ChRIS_ultron_backEnd PostgreSQL Database
    role: Backend development database
  creationTimestamp: null
  labels:
    io.kompose.service: chris-dev-db
  name: chris-dev-db
spec:
  replicas: 1
  selector:
    io.kompose.service: chris-dev-db
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/local: "true"
        io.kompose.service: chris-dev-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: chris_dev
            - name: POSTGRES_PASSWORD
              value: Chris1234
            - name: POSTGRES_USER
              value: chris
          image: ' '
          name: chris_dev_db
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: chris-dev-db-data
      restartPolicy: Always
      volumes:
        - name: chris-dev-db-data
          persistentVolumeClaim:
            claimName: chris-dev-db-data
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - chris-dev-db
        from:
          kind: ImageStreamTag
          name: chris-dev-db:13
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
