apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose convert --provider openshift --file docker-compose-cube-latest.yaml
    kompose.version: 1.17.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: chris-store
  name: chris-store
spec:
  replicas: 1
  selector:
    io.kompose.service: chris-store
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: chris-store
    spec:
      containers:
      - env:
        - name: DATABASE_HOST
          value: chris_store_db
        - name: DATABASE_PORT
          value: "5432"
        - name: DJANGO_ALLOWED_HOSTS
          value: '*'
        - name: DJANGO_CORS_ORIGIN_ALLOW_ALL
          value: "true"
        - name: DJANGO_CORS_ORIGIN_WHITELIST
          value: babymri.org
        - name: DJANGO_DB_MIGRATE
          value: "on"
        - name: DJANGO_SECRET_KEY
          value: secret
        - name: DJANGO_SECURE_PROXY_SSL_HEADER
        - name: DJANGO_SETTINGS_MODULE
          value: config.settings.production
        - name: DJANGO_USE_X_FORWARDED_HOST
          value: "false"
        - name: POSTGRESQL_DATABASE
          value: chris_store
        - name: POSTGRESQL_PASSWORD
          value: chirs1234
        - name: POSTGRESQL_USER
          value: chris
        - name: SWIFT_AUTH_URL
          value: http://swift:8080/auth/v1.0
        - name: SWIFT_CONTAINER_NAME
          value: store_users
        - name: SWIFT_KEY
          value: testing
        - name: SWIFT_USERNAME
          value: chris:chris1234
        image: ' '
        name: chris-store
        ports:
        - containerPort: 8010
        resources:
          limits:
            cpu: "100m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - chris-store
      from:
        kind: ImageStreamTag
        name: chris-store:2.0.1
    type: ImageChange
status: {}
