apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: chris-dev
  name: chris-dev
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations: null
      from:
        kind: DockerImage
        name: fnndsc/chris_ultron_backend:dev
      generation: null
      importPolicy: {}
      name: dev
      referencePolicy:
        type: ""
status:
  dockerImageRepository: ""
