apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
  name: chris-ui
spec:
  replicas: 1
  selector:
    io.kompose.service: chris-ui
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: chris-ui
    spec:
      serviceAccountName: pipeline
      containers:
        - args:
            - sirv
            - --quiet
            - --single
          env:
            - name: REACT-APP-CHRIS-UI-URL
              value: http://localhost:8000/api/v1/
          image: ghcr.io/fnndsc/chris_ui:latest
          name: chris-ui
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
