apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --provider openshift --file docker-compose-cube-latest.yaml
    kompose.version: 1.17.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: chris-store-ui
  name: chris-store-ui
spec:
  ports:
  - name: "8021"
    port: 8021
    targetPort: 3000
  selector:
    io.kompose.service: chris-store-ui
status:
  loadBalancer: {}
