apiVersion: v1
data:
  DATABASE_HOST: chris-store-db
  DATABASE_PORT: "5432"
  DJANGO_ALLOWED_HOSTS: '*'
  DJANGO_DB_MIGRATE: "on"
  DJANGO_CORS_ORIGIN_ALLOW_ALL: "true"
  DJANGO_CORS_ORIGIN_WHITELIST: babymri.org
  DJANGO_SECRET_KEY: secret
  DJANGO_SECURE_PROXY_SSL_HEADER: ""
  DJANGO_SETTINGS_MODULE: config.settings.production
  DJANGO_USE_X_FORWARDED_HOST: "false"
  POSTGRES_DB: chris_store
  POSTGRES_USER: chris
  POSTGRES_PASSWORD: chris1234
  SWIFT_CONTAINER_NAME: store_users
  SWIFT_USERNAME: chris:chris1234
  SWIFT_KEY: testing
  SWIFT_AUTH_URL: http://swift:8080/auth/v1.0
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: chris-store-ui-secrets-env
  name: chris-store-ui-secrets-env
