apiVersion: v1
kind: Service
metadata:
  name: chris-db
  labels:
    app: chris-db
    env: production
spec:
  selector:
    app: chris-db
    env: production
  ports:
    - port: 5432
      targetPort: 5432