apiVersion: v1
data:
  CELERY_BROKER_URL: amqp://queue:5672
  CHRIS_STORE_URL: http://chrisstore.local:8010/api/v1/
  DATABASE_HOST: chris_db
  DATABASE_PORT: "5432"
  DJANGO_ALLOWED_HOSTS: '*'
  DJANGO_CORS_ORIGIN_ALLOW_ALL: "true"
  DJANGO_CORS_ORIGIN_WHITELIST: babymri.org
  DJANGO_SECRET_KEY: secret
  DJANGO_SECURE_PROXY_SSL_HEADER: ""
  DJANGO_SETTINGS_MODULE: config.settings.production
  DJANGO_USE_X_FORWARDED_HOST: "false"
  POSTGRESQL_DATABASE: chris
  POSTGRESQL_PASSWORD: chris1234
  POSTGRESQL_USER: chris
  POSTGRES_DB: chris
  POSTGRES_USER: chris
  POSTGRES_PASSWORD: password1  
  POSTGRES_HOST_AUTH_METHOD: "trust"
  SWIFT_CONTAINER_NAME: users
  SWIFT_USERNAME: chris:chris1234
  SWIFT_KEY: testing
  STATIC_ROOT: /home/localuser/mod_wsgi-0.0.0.0:8000/htdocs/static/
  SWIFT_AUTH_URL: http://swift:8080/auth/v1.0
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: chris-secrets-env
  name: chris-secrets-env
