apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: chris-ui
  name: chris-ui
spec:
  replicas: 1
  selector:
    io.kompose.service: chris-ui
  strategy:
    resources: {}
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: chris-ui
    spec:
      containers:
        - args:
            - sirv
            - --quiet
            - --single
          env:
            - name: REACT-APP-CHRIS-UI-URL
              value: http://chris-ui:8020/api/v1/
          image: 'ghcr.io/fnndsc/chris_ui:3ca97e3'
          name: chris-ui
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0