apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: chrisomatic
  name: chrisomatic
spec:
  replicas: 1
  selector:
    io.kompose.service: chrisomatic
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/local: "true"
        io.kompose.service: chrisomatic
    spec:
      containers:
        - image: ' '
          name: chrisomatic
          resources: {}
          volumeMounts:
            - mountPath: /etc/chrisomatic
              name: chrisomatic-claim0
              readOnly: true
            - mountPath: /var/run/docker.sock
              name: chrisomatic-claim1
          workingDir: /etc/chrisomatic
      restartPolicy: Always
      volumes:
        - name: chrisomatic-claim0
          persistentVolumeClaim:
            claimName: chrisomatic-claim0
            readOnly: true
        - name: chrisomatic-claim1
          persistentVolumeClaim:
            claimName: chrisomatic-claim1
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - chrisomatic
        from:
          kind: ImageStreamTag
          name: chrisomatic:0.2.1
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
