apiVersion: apps/v1
kind: Deployment
metadata:
  name: chris-db
  labels:
    app: chris-db
    env: production
spec:
  replicas: 1  # stateful service, so only a single replica must be used
  selector:
    matchLabels:
      app: chris-db
      env: production
  template:
    metadata:
      name: chris-db
      labels:
        app: chris-db
        env: production
    spec:
      containers:
        - name: chris-db
          image: postgres:13
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: chris-db-config
          volumeMounts:
            - name: chrisdb
              mountPath: "/var/lib/postgresql/data"
      # Mount a persistent volume onto ChRIS DB
      volumes:
        - name: chrisdb
          persistentVolumeClaim:
            claimName: chrisdb