apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose convert --provider openshift --file docker-compose-cube-latest.yaml
    kompose.version: 1.17.0 (HEAD)
    name: ChRIS_store MySQL Database
  creationTimestamp: null
  labels:
    io.kompose.service: chris-store-db
  name: chris-store-db
spec:
  replicas: 1
  selector:
    io.kompose.service: chris-store-db
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: chris-store-db
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: chris_store
        - name: POSTGRES_PASSWORD
          value: chirs1234
        - name: POSTGRES_USER
          value: chris
        image: ' '
        name: chris-store-db
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: chris-store-db-data
      restartPolicy: Always
      volumes:
      - name: chris-store-db-data
        persistentVolumeClaim:
          claimName: chris-store-db-data
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - chris-store-db
      from:
        kind: ImageStreamTag
        name: chris-store-db:13
    type: ImageChange
status: {}
