apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: pfcon
  name: storebase
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1GB
status: {}