apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pfcon
  name: pfcon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pfcon
  strategy:
    resources: { }
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pfcon
    spec:
      serviceAccountName: pipeline
      containers:
        - env:
            - name: COMPUTE_SERVICE_URL
              value: http://pman:5010/api/v1/
            - name: PFCON_PASSWORD
              value: pfcon1234
            - name: PFCON_USER
              value: pfcon
            - name: SECRET_KEY
              value: secret
          image: ghcr.io/fnndsc/pfcon:next-5.0.0.a1.git.154d938
          name: pfcon
          ports:
            - containerPort: 5005
          command: ["/usr/local/bin/pfcon","--verbosity=5","--port=5005"]
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          volumeMounts:
            - mountPath: /var/local/storeBase
              name: remote
      restartPolicy: Always
      volumes:
        - name: remote
          persistentVolumeClaim:
            claimName: remote
        - emptyDir: {}
          name: pfcon
status: {}