apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pman
  name: pman
spec:
  replicas: 1
  strategy:
    resources: { }
    type: Recreate
  selector:
    matchLabels:
      app: pman
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pman
    spec:
      serviceAccountName: pipeline
      containers:
      - command: ["/usr/local/bin/pman","--verbosity=5","--port=5010","--tokenPath=/etc/pman/auth/pman_config.cfg"]
        args: ["-w", "5", "-b", "0.0.0.0:30010", "-t",  "200", "pman.wsgi:application"]
        envFrom:
          - configMapRef:
              name: chris-secrets-env
        image: 'fnndsc/pman'
        name: pman
        ports:
        - containerPort: 30010
        resources:
          limits:
            cpu: "100m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: pman-claim0
        - mountPath: /entrypoint.sh
          name: pman-claim1
          readOnly: true
        - mountPath: /var/local/storeBase
          name: pman-storebase
      restartPolicy: Always
      volumes:
      - name: pman-claim0
        persistentVolumeClaim:
          claimName: pman-claim0
      - name: pman-claim1
        persistentVolumeClaim:
          claimName: pman-claim1
          readOnly: true
      - name: pman-storebase
        persistentVolumeClaim:
          claimName: pman-storebase  
status: {}
