apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: pman
  name: pman
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: fnndsc/pman:next-4.0.0.a1.git.c245243
    generation: null
    importPolicy: {}
    name: next-4.0.0.a1.git.c245243
status:
  dockerImageRepository: ""
