apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pman
  name: pman
spec:
  replicas: 1
  strategy:
    resources: { }
    type: Recreate
  selector:
    matchLabels:
      app: pman
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pman
    spec:
      serviceAccountName: pipeline
      containers:
      - command: ["gunicorn", "--bind", "0.0.0.0:5010", "--workers", "2", "--timeout", "20", "pman.wsgi:application"]
        envFrom:
          - configMapRef:
              name: chris-secrets-env
        image: 'fnndsc/pman:next-4.0.0.a1.git.c245243'
        name: pman
        ports:
        - containerPort: 30010
        resources:
          limits:
            cpu: "300m"
            memory: "256Mi"
          requests:
            cpu: "300m"
            memory: "256Mi"
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: pman-claim0
        - mountPath: /entrypoint.sh
          name: pman-claim1
          readOnly: true
        - mountPath: /var/local/storeBase
          name: pman-storebase
      restartPolicy: Always
      volumes:
      - name: pman-claim0
        persistentVolumeClaim:
          claimName: pman-claim0
      - name: pman-claim1
        persistentVolumeClaim:
          claimName: pman-claim1
          readOnly: true
      - name: pman-storebase
        persistentVolumeClaim:
          claimName: pman-storebase  
status: {}
