apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: queue
  name: queue
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations: null
      from:
        kind: DockerImage
        name: rabbitmq:3
      generation: null
      importPolicy: {}
      name: "3"
      referencePolicy:
        type: ""
status:
  dockerImageRepository: ""
