apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: queue
  name: queue
spec:
  containers:
  - image: rabbitmq:3
    name: queue
    resources:
      limits:
        cpu: "800m"
        memory: "800Mi"
      requests:
        cpu: "600m"
        memory: "400Mi"
  restartPolicy: OnFailure
status: {}
