apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: queue
  name: queue
spec:
  containers:
  - image: rabbitmq:3
    name: queue
    resources: {}
  restartPolicy: OnFailure
status: {}
