apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    name: ChRIS_ultron_backEnd Asynchronous Task Queue
    role: Backend development async task queue
  creationTimestamp: null
  labels:
    io.kompose.service: queue
  name: queue
spec:
  replicas: 1
  selector:
    io.kompose.service: queue
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/local: "true"
        io.kompose.service: queue
    spec:
      containers:
        - image: ' '
          name: queue
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/rabbitmq
              name: queue-data
      hostname: queue
      restartPolicy: Always
      volumes:
        - name: queue-data
          persistentVolumeClaim:
            claimName: queue-data
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - queue
        from:
          kind: ImageStreamTag
          name: queue:3
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
