apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: queuedb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      volume: queuedb