apiVersion: v1
kind: PersistentVolume
metadata:
  name: queuedb
  labels:
    volume: queuedb
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  # Mount a physical dir in the HOST onto the ChRIS async queue. This dir
  # is given by the STORAGEBASE env variable substitution.