apiVersion: v1
kind: Pod
metadata:
  annotations:
    name: ChRIS_ultron_backEnd Periodic Tasks Scheduler
    role: Backend development periodic tasks scheduler
  creationTimestamp: null
  labels:
    io.kompose.network/local: "true"
    io.kompose.service: scheduler
  name: scheduler
spec:
  containers:
    - args:
        - celery
        - -A
        - core
        - beat
        - -l
        - info
        - --pidfile
        - /home/localuser/celerybeat.pid
        - --scheduler
        - django_celery_beat.schedulers:DatabaseScheduler
      env:
        - name: DJANGO_COLLECTSTATIC
          value: "off"
        - name: DJANGO_DB_MIGRATE
          value: "off"
        - name: DJANGO_SETTINGS_MODULE
          value: config.settings.local
      image: chris:dev
      name: scheduler
      resources: {}
      volumeMounts:
        - mountPath: /home/localuser/chris_backend
          name: scheduler-claim0
  restartPolicy: OnFailure
  volumes:
    - name: scheduler-claim0
      persistentVolumeClaim:
        claimName: scheduler-claim0
status: {}
