apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose convert --provider openshift --file docker-compose-cube-latest.yaml
    kompose.version: 1.17.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: swarm-status
  name: swarm-status
spec:
  replicas: 1
  selector:
    io.kompose.service: swarm-status
  strategy:
    resources:
      limits:
        cpu: "100m"
        memory: "256Mi"
      requests:
        cpu: "100m"
        memory: "256Mi"
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: swarm-status
    spec:
      containers:
      - command:
        - /entrypoint.sh
        image: ' '
        name: swarm-status
        resources: {}
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: swarm-status-claim0
        - mountPath: /entrypoint.sh
          name: swarm-status-claim1
      restartPolicy: Always
      volumes:
      - name: swarm-status-claim0
        persistentVolumeClaim:
          claimName: swarm-status-claim0
      - name: swarm-status-claim1
        persistentVolumeClaim:
          claimName: swarm-status-claim1
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - swarm-status
      from:
        kind: ImageStreamTag
        name: swarm-status:latest
    type: ImageChange
status: {}
