apiVersion: v1
kind: Service
metadata:
  annotations:
    name: Swift
    role: Swift object storage service
  creationTimestamp: null
  labels:
    io.kompose.service: swift-service
  name: swift-service
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: swift-service
status:
  loadBalancer: {}
