apiVersion: apps/v1
kind: Deployment
metadata:
  name: swift
  labels:
    app: swift
    env: production
spec:
  replicas: 1  # stateful service, so only a single replica must be used
  selector:
    matchLabels:
      app: swift
      env: production
  template:
    metadata:
      name: swift
      labels:
        app: swift
        env: production
    spec:
      containers:
        - name: swift
          image: fnndsc/docker-swift-onlyone
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: swift-config
          volumeMounts:
            - name: swiftdb
              mountPath: "/srv"
      # Mount a persistent volume onto the Swift object storage
      volumes:
        - name: swiftdb
          persistentVolumeClaim:
            claimName: swiftdb