apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: swift
  name: swift
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: fnndsc/docker-swift-onlyone:latest
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
