apiVersion: v1
kind: Service
metadata:
  name: swift
  labels:
    app: swift
    env: production
spec:
  type: NodePort
  selector:
    app: swift
    env: production
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080