apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    name: ChRIS_ultron_backEnd Asynchronous Tasks Worker
    role: Backend development async task worker
  creationTimestamp: null
  labels:
    io.kompose.service: worker
  name: worker
spec:
  replicas: 1
  selector:
    io.kompose.service: worker
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/local: "true"
        io.kompose.network/remote: "true"
        io.kompose.service: worker
    spec:
      containers:
        - args:
            - celery
            - -A
            - core
            - worker
            - -c
            - "3"
            - -l
            - DEBUG
            - -Q
            - main1,main2
          env:
            - name: CELERY_RDB_HOST
              value: 0.0.0.0
            - name: CELERY_RDB_PORT
              value: "6900"
            - name: DJANGO_COLLECTSTATIC
              value: "off"
            - name: DJANGO_DB_MIGRATE
              value: "off"
            - name: DJANGO_SETTINGS_MODULE
              value: config.settings.local
          image: ' '
          name: worker
          ports:
            - containerPort: 6900
            - containerPort: 6901
            - containerPort: 6902
            - containerPort: 6903
            - containerPort: 6904
            - containerPort: 6905
          resources: {}
          volumeMounts:
            - mountPath: /home/localuser/chris_backend
              name: worker-claim0
      restartPolicy: Always
      volumes:
        - name: worker-claim0
          persistentVolumeClaim:
            claimName: worker-claim0
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - worker
        from:
          kind: ImageStreamTag
          name: worker:dev
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
